### ISSUE TITLE
MLB avec LazyMan.

### ISSUE THREAD

**Issue by Benkellie** [jwallet/go-mlbam-proxy#3]
Salut. 
Comme je tes déjà expliqué, je ne parle pas anglais alors si ses déjà expliqué je suis désolée mes pourrais tu me dire comment regarder le Baseball sur LazyMan s'il vous plaît.
Merci.

**Comment by jwallet** [comment]
apparemment le baseball est hors service presentement... voir [/r/lazyMan](https://www.reddit.com/r/LazyMan/) ou [github LazyMan](https://github.com/StevensNJD4/LazyMan)
